"""Deliver renders a notebook to the SYNC-EXCLUDED outbox with value-free provenance.

The marimo export subprocess is faked (it would execute the notebook and needs a real
kernel); these pin the outbox location, the provenance footer, the activity receipt,
and the failure/refusal paths.
"""

from __future__ import annotations

import json
import subprocess

import pytest

from mooring import activity, inputs, sync
from mooring.app import deliver
from mooring.config import Config

# A minimal real marimo notebook (has the `= marimo.App(` marker openable_kind requires).
NOTEBOOK = "import marimo\n\napp = marimo.App()\n\n\n@app.cell\ndef _():\n    return\n"


def _cfg(tmp_path):
    return Config(client_id="cid", owner="acme", repo="nbs", workspace_path=str(tmp_path / "ws"))


def _fake_export(cmd, **kwargs):
    """Stand in for `marimo export html`: write a minimal HTML at the `-o` target."""
    out = None
    for i, tok in enumerate(cmd):
        if tok == "-o":
            out = cmd[i + 1]
            break
    from pathlib import Path

    path = Path(out)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("<html><body><h1>Report</h1></body></html>", encoding="utf-8")
    return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")


def test_outbox_and_state_dir_are_structurally_unsyncable():
    # The load-bearing guarantee: a rendered artifact (or a checks receipt / the pylib
    # payload) under .mooring can NEVER be a sync candidate, even with a custom exclude.
    for rel in (
        ".mooring/outbox/report.html",
        ".mooring/outbox/sales/sales-20260101.html",
        ".mooring/checks/notebooks__nb.py.json",
        ".mooring/pylib/mooring_checks.py",
    ):
        assert sync.is_synced_path(rel) is False
        assert sync.is_synced_path(rel, exclude=("*.html",)) is False


def test_deliver_writes_html_to_outbox_with_provenance(tmp_path, monkeypatch):
    cfg = _cfg(tmp_path)
    ws = cfg.workspace()
    (ws / "notebooks").mkdir(parents=True)
    (ws / "notebooks" / "sales.py").write_text(NOTEBOOK, encoding="utf-8")
    monkeypatch.setattr(deliver.subprocess, "run", _fake_export)

    result = deliver.deliver_html(cfg, "notebooks/sales.py")

    assert result.out_path.is_file()
    assert ".mooring/outbox/" in result.out_rel
    assert result.out_path.name.startswith("sales-")
    html = result.out_path.read_text("utf-8")
    assert "Generated by mooring from acme/nbs" in html
    assert "notebook notebooks/sales.py" in html
    # Never pushed (not in the manifest): NO GitHub link, and the footer says so —
    # a blob link would 404 and the @commit claim would be false.
    assert "not yet pushed" in html
    assert "View on GitHub" not in html
    # The exported HTML lives under the sync-excluded outbox.
    assert sync.is_synced_path(result.out_rel) is False


def test_deliver_links_to_github_only_when_synced(tmp_path, monkeypatch):
    cfg = _cfg(tmp_path)
    ws = cfg.workspace()
    (ws / "notebooks").mkdir(parents=True)
    (ws / "notebooks" / "sales.py").write_text(NOTEBOOK, encoding="utf-8")
    monkeypatch.setattr(deliver.subprocess, "run", _fake_export)

    class _Mft:  # the notebook is tracked on the remote at this head commit
        head_commit = "abcdef1234567890"
        files = {"notebooks/sales.py": "blobsha"}

    monkeypatch.setattr(deliver.manifest, "load", lambda ws: _Mft())
    result = deliver.deliver_html(cfg, "notebooks/sales.py")
    html = result.out_path.read_text("utf-8")
    assert "acme/nbs@abcdef1" in html  # short head commit
    assert "View on GitHub" in html
    assert "/blob/" in html and "notebooks/sales.py" in html


def test_deliver_stamps_value_free_input_fingerprints(tmp_path, monkeypatch):
    # When the notebook recorded input fingerprints (via mooring_inputs) during the
    # render, Deliver stamps them into the provenance footer — filename + content hash +
    # shape, never a value — so the reader can answer "same inputs, same numbers?".
    cfg = _cfg(tmp_path)
    ws = cfg.workspace()
    (ws / "notebooks").mkdir(parents=True)
    (ws / "notebooks" / "sales.py").write_text(NOTEBOOK, encoding="utf-8")
    rec_dir = inputs.inputs_dir(ws)
    rec_dir.mkdir(parents=True)
    (rec_dir / "notebooks__sales.py.json").write_text(
        json.dumps(
            {
                "notebook": "notebooks/sales.py",
                "updated": "2026-07-03T00:00:00+00:00",
                "inputs": {
                    "sales": {
                        "path": "data/sales.csv",
                        "sha": "abcdef1234567890",
                        "rows": 1000,
                        "cols": 12,
                        "schema": [["id", "Int64"]],
                        "changed": False,
                    }
                },
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.setattr(deliver.subprocess, "run", _fake_export)

    result = deliver.deliver_html(cfg, "notebooks/sales.py")
    html = result.out_path.read_text("utf-8")
    assert "Inputs: sales (abcdef1, 1000×12)" in html


def test_deliver_records_a_value_free_activity_entry(tmp_path, monkeypatch):
    cfg = _cfg(tmp_path)
    ws = cfg.workspace()
    ws.mkdir(parents=True)
    (ws / "sales.py").write_text(NOTEBOOK, encoding="utf-8")
    monkeypatch.setattr(deliver.subprocess, "run", _fake_export)

    deliver.deliver_html(cfg, "sales.py")

    entries = activity.read(ws)
    assert entries and entries[0]["op"] == "deliver"
    assert entries[0]["path"] == "sales.py"


def test_deliver_local_mode_footer_has_no_github_link(tmp_path, monkeypatch):
    # No repo configured -> the provenance footer omits the GitHub link and says local.
    cfg = Config(client_id="", owner="", repo="", workspace_path=str(tmp_path / "ws"))
    ws = cfg.workspace()
    ws.mkdir(parents=True)
    (ws / "sales.py").write_text(NOTEBOOK, encoding="utf-8")
    monkeypatch.setattr(deliver.subprocess, "run", _fake_export)

    result = deliver.deliver_html(cfg, "sales.py")
    html = result.out_path.read_text("utf-8")
    assert "a local workspace" in html
    assert "View on GitHub" not in html


def test_deliver_refuses_a_plain_module(tmp_path):
    cfg = _cfg(tmp_path)
    ws = cfg.workspace()
    ws.mkdir(parents=True)
    (ws / "helpers.py").write_text("def f():\n    return 1\n", encoding="utf-8")
    with pytest.raises(deliver.DeliverError):
        deliver.deliver_html(cfg, "helpers.py")


def test_deliver_raises_on_render_failure(tmp_path, monkeypatch):
    cfg = _cfg(tmp_path)
    ws = cfg.workspace()
    ws.mkdir(parents=True)
    (ws / "sales.py").write_text(NOTEBOOK, encoding="utf-8")

    def _fail(cmd, **kwargs):
        return subprocess.CompletedProcess(cmd, 1, stdout="", stderr="ValueError: boom")

    monkeypatch.setattr(deliver.subprocess, "run", _fail)
    with pytest.raises(deliver.DeliverError):
        deliver.deliver_html(cfg, "sales.py")


def test_deliver_rejects_a_path_escaping_the_workspace(tmp_path):
    cfg = _cfg(tmp_path)
    cfg.workspace().mkdir(parents=True)
    with pytest.raises(ValueError):
        deliver.deliver_html(cfg, "../secret.py")
