"use strict";

// Unit tests for the hub's lineage wording (lineage_fmt.js). Zero deps: Node's built-in
// runner + assert. Run with: node --test tests/js/
//
// The contract under test is an HONESTY one, so most of these are about what must NOT
// appear. The server never sends a zero count, and nothing here may invent one, invent a
// "nothing depends on this", or state a claim without its date.

const { test } = require("node:test");
const assert = require("node:assert/strict");
const L = require("../../src/mooring/hub/static/lineage_fmt.js");

const fresh = (extra) => Object.assign({ as_of: "2026-07-30T09:00:00+00:00", stale: false }, extra);
const stale = (extra) => Object.assign({ as_of: "2026-01-05T09:00:00+00:00", stale: true }, extra);

test("badge states the readers it has", () => {
  const one = L.badge(fresh({ readers: 1 }));
  assert.equal(one.text, "⇄ 1 notebook reads this");
  const many = L.badge(fresh({ readers: 3 }));
  assert.equal(many.text, "⇄ 3 notebooks read this");
});

test("badge on a GENERATED file claims only that, never '0 readers'", () => {
  // The governing case: a derived output is the file most likely to be read by a
  // dashboard or a spreadsheet mooring cannot see, so a confident "0 notebooks read
  // this" would be both authoritative-looking and probably false. The payload omits the
  // count entirely and the wording must not reintroduce it — in the tooltip either,
  // which is where a zero would look most like a finding.
  const { text, title } = L.badge(fresh({ writers: 1 }));
  assert.equal(text, "⇄ generated by 1");
  assert.ok(!/\b0\b/.test(text), text);
  assert.ok(!/\b0\b/.test(title), title);
  assert.ok(!/read/.test(text), "must make no claim about readers at all");
  assert.match(title, /1 notebook generates it/);
});

test("badge makes no claim about writers when there are none", () => {
  const { text, title } = L.badge(fresh({ readers: 2 }));
  assert.ok(!/generate|written/.test(text), text);
  assert.ok(!/\b0\b/.test(title), title);
});

test("badge returns null when the payload supports no claim", () => {
  // No badge at all beats a badge that says nothing — the row must stay silent.
  assert.equal(L.badge({}), null);
  assert.equal(L.badge(null), null);
  assert.equal(L.badge(undefined), null);
  assert.equal(L.badge({ readers: 0, writers: 0 }), null);
});

test("badge title always carries the floor caveat", () => {
  const { title } = L.badge(fresh({ readers: 3 }));
  assert.match(title, /floor/);
  assert.match(title, /no badge is not evidence a file is unused/);
});

test("a claim is dated, and a stale one says so in the badge text itself", () => {
  assert.equal(L.badge(fresh({ readers: 2 })).text, "⇄ 2 notebooks read this");
  assert.match(L.badge(fresh({ readers: 2 })).title, /recorded 2026-07-30/);
  // Once stale the date is promoted out of the tooltip: it has stopped being a current
  // fact, and a tooltip nobody hovers is not "surfaced".
  const old = L.badge(stale({ readers: 2 }));
  assert.equal(old.text, "⇄ 2 notebooks read this (last recorded 2026-01-05, not confirmed since)");
});

test("an undated claim is labelled, not silently presented as current", () => {
  // No timestamp means the claim's age cannot be established — which is exactly the one a
  // user should re-check, so it is treated as stale and says "never dated" on the row.
  assert.equal(L.recency({ readers: 1 }), "never dated");
  assert.match(L.badge({ readers: 1 }).title, /never dated/);
  assert.equal(L.badge({ readers: 1, stale: true }).text, "⇄ 1 notebook reads this (never dated)");
});

test("pullImpact: only states where the pull actually replaces or removes the file", () => {
  const row = (state) => ({ path: `${state}.csv`, state, lineage: fresh({ readers: 2 }) });
  const hits = L.pullImpact([
    row("remote changed"),
    row("deleted remotely"),
    // "new remote" has no local copy to overwrite, and pull SKIPS a conflict — warning
    // about either would be a warning the user cannot act on.
    row("new remote"),
    row("conflict"),
    row("synced"),
    row("modified"),
  ]);
  assert.deepEqual(hits.map((h) => h.state), ["deleted remotely", "remote changed"]);
});

test("pullImpact covers a file YOUR notebook generates, not just ones others read", () => {
  // Symmetric with the badge: a pull landing the team's copy over an extract you
  // regenerate is the same surprise from the other direction.
  const hits = L.pullImpact([
    { path: "out.csv", state: "remote changed", lineage: fresh({ writers: 1 }) },
  ]);
  assert.equal(hits.length, 1);
  assert.match(L.impactLine(hits[0]), /replaces a file 1 notebook generates/);
});

test("pullImpact: a file with nothing recorded is absent, never a zero entry", () => {
  assert.deepEqual(
    L.pullImpact([
      { path: "a.csv", state: "remote changed" },
      { path: "b.csv", state: "remote changed", lineage: { readers: 0, writers: 0 } },
    ]),
    []
  );
  assert.deepEqual(L.pullImpact([]), []);
  assert.deepEqual(L.pullImpact(undefined), []);
});

test("pullImpact: busiest file first, then by path", () => {
  const row = (path, readers) => ({ path, state: "remote changed", lineage: fresh({ readers }) });
  const hits = L.pullImpact([row("z.csv", 1), row("b.csv", 4), row("a.csv", 1)]);
  assert.deepEqual(hits.map((h) => h.path), ["b.csv", "a.csv", "z.csv"]);
});

test("impactLine dates every line and uses the right verb for a remote deletion", () => {
  const [replaced] = L.pullImpact([
    { path: "s.csv", state: "remote changed", lineage: fresh({ readers: 2 }) },
  ]);
  assert.equal(L.impactLine(replaced), "  s.csv — replaces a file 2 notebooks read (recorded 2026-07-30)");
  const [removed] = L.pullImpact([
    { path: "s.csv", state: "deleted remotely", lineage: stale({ readers: 1 }) },
  ]);
  assert.match(L.impactLine(removed), /removes a file 1 notebook reads/);
  assert.match(L.impactLine(removed), /last recorded 2026-01-05, not confirmed since/);
});

test("impactWarning is empty when nothing is recorded — never a reassurance", () => {
  // A destructive confirm must read exactly as it did before rather than gain a
  // "nothing depends on this", which is a claim lineage cannot make.
  assert.equal(L.impactWarning(undefined), "");
  assert.equal(L.impactWarning({}), "");
  assert.equal(L.impactWarning({ readers: 0, writers: 0 }), "");
});

test("impactWarning names the dependants and dates them", () => {
  const said = L.impactWarning(fresh({ readers: 3, writers: 1 }));
  assert.match(said, /3 notebooks read it/);
  assert.match(said, /1 notebook generates it/);
  assert.match(said, /recorded 2026-07-30/);
  assert.match(said, /there may be more/);
});

test("exposes its API as a bare global AND on window (the files_tree.js idiom)", () => {
  const fs = require("node:fs");
  const path = require("node:path");
  const vm = require("node:vm");
  const src = fs.readFileSync(
    path.join(__dirname, "..", "..", "src", "mooring", "hub", "static", "lineage_fmt.js"),
    "utf8"
  );
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(src + "\n;window.__bare = LineageFmt;", sandbox);
  assert.equal(sandbox.window.__bare, sandbox.window.LineageFmt);
  assert.equal(typeof sandbox.window.LineageFmt.badge, "function");
});
